---
- hosts: 127.0.0.1
  connection: local
  vars_files:
    - secrets.yaml
  tasks:
    - name: Template digital_ocean.ini locally.
      template:
        src: templates/digital_ocean.ini.j2
        dest: inventory/digital_ocean.ini
        mode: 0600

    - name: Template terraform.tfvars locally.
      template:
        src: templates/terraform.tfvars.j2
        dest: terraform.tfvars
        mode: 0600

- hosts: api-canaries
  tasks:
    - name: Template the Python script.
      template:
        src: templates/digitalocean_api_canary.py.j2
        dest: "{{ ansible_env.HOME }}/digitalocean_api_canary.py"
        mode: 0755

    - name: Install pip3.
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Install the requests module.
      pip:
        name: requests

    - name: Template the systemd service.
      template:
        src: templates/digitalocean_api_canary.service.j2
        dest: /etc/systemd/system/digitalocean_api_canary.service

    - name: Template the systemd timer.
      template:
        src: templates/digitalocean_api_canary.timer.j2
        dest: /etc/systemd/system/digitalocean_api_canary.timer

    - name: Activate the systemd timer.
      systemd:
        name: digitalocean_api_canary.timer
        state: started
        daemon_reload: yes
