---
- name: Set up the local machine.
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - secrets.yaml
  roles:
    - local-machine

- name: Set up the remote infrastructure.
  hosts: api-canaries
  vars_files:
    - secrets.yaml
  roles:
    - canary
    - role: elastic-beats
      tags:
        - elasticsearch-logging
