---
- name: Template the Python script.
  template:
    src: digitalocean_api_canary.py.j2
    dest: "{{ ansible_env.HOME }}/digitalocean_api_canary.py"
    mode: 0755

- name: Install pip3.
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Install the requests module.
  pip:
    name: requests

- name: Template the systemd units.
  template:
    src: "{{ item }}.j2"
    dest: /etc/systemd/system/{{ item }}
  loop:
    - digitalocean_api_canary.service
    - digitalocean_api_canary.timer
  notify: Activate the systemd timer.
